#!/usr/bin/env python3
"""Generate frontend/src/data/astanaGeometry.ts from astana_districts.geojson.

Projection matches the approved "Astana Scheme":
  x = (lon - minLon) * cos(51.15 deg) * s,  y = (maxLat - lat) * s
The viewBox is cropped to the data bounds plus a small padding. Rings are
simplified with Douglas-Peucker (~40 m) and coordinates rounded to 0.1.

Usage: python3 product.v1/scripts/build_geometry.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "frontend" / "src" / "data" / "astana_districts.geojson"
OUT = ROOT / "frontend" / "src" / "data" / "astanaGeometry.ts"

IDS = {
    "район Есиль": "esil",
    "район Алматы": "almaty",
    "район Сарыарка": "saryarka",
    "район Байконур": "baikonur",
    "район Нура": "nura",
}
ORDER = ["baikonur", "saryarka", "almaty", "esil", "nura"]
KX = math.cos(math.radians(51.15))
TARGET_W = 600.0  # viewBox width of the data area, before padding
PAD = 12.0        # padding around the data, viewBox units
TOL_M = 40.0      # simplification tolerance, metres
M_PER_DEG_LAT = 111_320.0
# fraction of viewBox (width, height); Baikonur moved up-right so its pill
# clears the pill of thin Saryarka.
LABEL_NUDGE = {"esil": (0.0, -0.03), "baikonur": (0.03, -0.035)}


def dp(points, tol):
    """Douglas-Peucker on a list of (x, y); keeps endpoints."""
    if len(points) < 3:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = points[a]
        bx, by = points[b]
        dx, dy = bx - ax, by - ay
        seg = math.hypot(dx, dy)
        best, idx = -1.0, -1
        for i in range(a + 1, b):
            px, py = points[i]
            if seg == 0:
                d = math.hypot(px - ax, py - ay)
            else:
                d = abs(dy * px - dx * py + bx * ay - by * ax) / seg
            if d > best:
                best, idx = d, i
        if best > tol and idx > 0:
            keep[idx] = True
            stack.append((a, idx))
            stack.append((idx, b))
    return [p for p, k in zip(points, keep) if k]


def ring_area_centroid(ring):
    a = cx = cy = 0.0
    n = len(ring)
    for i in range(n):
        x0, y0 = ring[i]
        x1, y1 = ring[(i + 1) % n]
        c = x0 * y1 - x1 * y0
        a += c
        cx += (x0 + x1) * c
        cy += (y0 + y1) * c
    a *= 0.5
    if a == 0:
        xs, ys = zip(*ring)
        return 0.0, (sum(xs) / n, sum(ys) / n)
    return abs(a), (cx / (6 * a), cy / (6 * a))


def fmt(v):
    s = f"{round(v, 1):.1f}"
    return s[:-2] if s.endswith(".0") else s


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    feats = {}
    for f in data["features"]:
        did = IDS[f["properties"]["name_ru"]]
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        feats[did] = polys

    lons = [p[0] for polys in feats.values() for poly in polys for ring in poly for p in ring]
    lats = [p[1] for polys in feats.values() for poly in polys for ring in poly for p in ring]
    min_lon, max_lon, min_lat, max_lat = min(lons), max(lons), min(lats), max(lats)
    s = TARGET_W / ((max_lon - min_lon) * KX)
    data_h = (max_lat - min_lat) * s
    width, height = TARGET_W + 2 * PAD, data_h + 2 * PAD
    tol = TOL_M / M_PER_DEG_LAT * s

    def proj(lon, lat):
        return ((lon - min_lon) * KX * s + PAD, (max_lat - lat) * s + PAD)

    out = {}
    for did in ORDER:
        parts = []
        best = (-1.0, (0.0, 0.0))
        for poly in feats[did]:
            for ri, ring in enumerate(poly):
                pts = [proj(lon, lat) for lon, lat in ring]
                if len(pts) > 1 and pts[0] == pts[-1]:
                    pts = pts[:-1]
                if ri == 0:
                    area, c = ring_area_centroid(pts)
                    if area > best[0]:
                        best = (area, c)
                simp = dp(pts + [pts[0]], tol)[:-1]
                if len(simp) < 3:
                    continue
                parts.append("M" + "L".join(f"{fmt(x)} {fmt(y)}" for x, y in simp) + "Z")
        lx, ly = best[1]
        nx, ny = LABEL_NUDGE.get(did, (0.0, 0.0))
        out[did] = ("".join(parts), (lx + nx * width, ly + ny * height))

    lines = [
        "// Контуры пяти районов Астаны для CityMap.",
        "// Data © OpenStreetMap contributors, ODbL 1.0 (https://www.openstreetmap.org/copyright).",
        f"// Simplified ~{int(TOL_M)} m (Douglas-Peucker), coords rounded to 0.1 viewBox units.",
        "// GENERATED by scripts/build_geometry.py from astana_districts.geojson — do not edit by hand.",
        "",
        "import type { DistrictId } from './dataset'",
        "",
        f"export const ASTANA_VIEWBOX: {{ width: number; height: number }} = {{ width: {fmt(width)}, height: {fmt(height)} }}",
        "",
        "/** path — SVG d в единицах viewBox; label — точка подписи (центроид крупнейшего контура). */",
        "export const ASTANA_DISTRICTS: Record<DistrictId, { path: string; label: [number, number] }> = {",
    ]
    for did in ORDER:
        path, (lx, ly) = out[did]
        lines.append(f"  {did}: {{")
        lines.append(f"    label: [{fmt(lx)}, {fmt(ly)}],")
        lines.append(f"    path: '{path}',")
        lines.append("  },")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes), viewBox {fmt(width)}x{fmt(height)}")


if __name__ == "__main__":
    main()
